services:
  db:
    build:
      context: ./db    
      dockerfile: Dockerfile
    container_name: db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: salesPred314!
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

  api:
    build:
      context: ./SalesDatePrediction-back
      dockerfile: SalesDatePrediction.API/Dockerfile
    container_name: api_container
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=StoreSample;User Id=sa;Password=salesPred314!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./SalesDatePrediction-web-app
      dockerfile: Dockerfile
    container_name: webapp_container
    ports:
      - "4200:4000"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sql_data:
